-- Migration: Create AURA Discovery Engine Tables
-- Date: 2026-09-16
-- Description: Tables for multi-strategy recommendation system with attribution,
--              pre-download pipeline, and adaptive feedback loop.

-- =============================================================================
-- discovery_items: Recommended items generated by the discovery engine.
-- NEVER physically deleted (soft-delete via is_expired + file_purged).
-- This preserves feedback history for weight recomputation.
-- =============================================================================
CREATE TABLE IF NOT EXISTS discovery_items (
    id TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    -- Attribution: which strategy produced this recommendation
    source_strategy TEXT NOT NULL,              -- 'artist_radar', 'genre_drift', 'artist_radio', 'wildcard'
    source_artist_name TEXT,                    -- AURA artist that triggered the recommendation (radar/radio)
    source_deezer_artist_id BIGINT,             -- Deezer artist ID that triggered the recommendation
    reason_text TEXT,                           -- Human-readable explanation, e.g. "Fans de Daft Punk aiment aussi..."

    -- Recommended content (Deezer metadata)
    deezer_track_id BIGINT NOT NULL,
    deezer_album_id BIGINT,
    deezer_artist_id BIGINT NOT NULL,
    track_title TEXT NOT NULL,
    artist_name TEXT NOT NULL,
    album_title TEXT,
    cover_url TEXT,
    duration_ms INTEGER,
    release_date TEXT,                          -- ISO date string
    record_type TEXT,                           -- 'album', 'single', 'ep', 'compile'
    preview_url TEXT,                           -- Deezer 30s MP3 preview URL

    -- Pre-download state
    download_status TEXT NOT NULL DEFAULT 'pending',  -- 'pending', 'downloading', 'ready', 'failed'
    download_job_id TEXT,                       -- FK to download_jobs.id if pre-download was triggered
    aura_track_id TEXT,                         -- AURA track_id once downloaded (trk_deezer_...)

    -- Scoring
    score REAL NOT NULL DEFAULT 0.0,

    -- Lifecycle (soft-delete: rows are NEVER deleted)
    batch_id TEXT NOT NULL,                     -- Identifies the generation batch
    is_expired BOOLEAN NOT NULL DEFAULT FALSE,  -- Set when expires_at is passed
    file_purged BOOLEAN NOT NULL DEFAULT FALSE, -- Set when the audio file has been purged from disk
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ DEFAULT now() + INTERVAL '14 days',

    CONSTRAINT uq_discovery_user_track_batch UNIQUE(user_id, deezer_track_id, batch_id)
);

-- Active feed: non-expired items ready for display, ordered by score
CREATE INDEX idx_discovery_active_feed ON discovery_items(user_id, score DESC)
    WHERE is_expired = FALSE;

-- Purge candidates: non-expired, non-purged items for the cleanup job
CREATE INDEX idx_discovery_purge_candidates ON discovery_items(user_id, expires_at)
    WHERE is_expired = FALSE AND file_purged = FALSE;

-- Batch lookup
CREATE INDEX idx_discovery_batch ON discovery_items(batch_id);

-- Dedup lookups: recently proposed tracks
CREATE INDEX idx_discovery_dedup ON discovery_items(user_id, deezer_track_id, created_at DESC);


-- =============================================================================
-- discovery_feedback: User actions on discovery items.
-- No ON DELETE CASCADE on discovery_item_id (items are never deleted).
-- =============================================================================
CREATE TABLE IF NOT EXISTS discovery_feedback (
    id TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    discovery_item_id TEXT NOT NULL REFERENCES discovery_items(id),

    -- Observed actions
    was_seen BOOLEAN DEFAULT FALSE,
    was_played BOOLEAN DEFAULT FALSE,
    was_completed BOOLEAN DEFAULT FALSE,       -- Listened > 80%
    was_skipped BOOLEAN DEFAULT FALSE,
    was_liked BOOLEAN DEFAULT FALSE,
    was_added_to_playlist BOOLEAN DEFAULT FALSE,
    was_downloaded BOOLEAN DEFAULT FALSE,

    -- Timing
    first_seen_at TIMESTAMPTZ,
    first_played_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT uq_feedback_user_item UNIQUE(user_id, discovery_item_id)
);

CREATE INDEX idx_feedback_item ON discovery_feedback(discovery_item_id);


-- =============================================================================
-- discovery_strategy_weights: Adaptive ratios per strategy per user.
-- Converge toward user preferences via normalized conversion rates.
-- =============================================================================
CREATE TABLE IF NOT EXISTS discovery_strategy_weights (
    user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    artist_radar_weight REAL NOT NULL DEFAULT 0.45,
    genre_drift_weight REAL NOT NULL DEFAULT 0.25,
    artist_radio_weight REAL NOT NULL DEFAULT 0.20,
    wildcard_weight REAL NOT NULL DEFAULT 0.10,
    total_feedback_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now()
);


-- =============================================================================
-- artist_graph_cache: Cached Deezer /artist/{id}/related results (TTL 7 days).
-- Avoids redundant Deezer calls across batches.
-- =============================================================================
CREATE TABLE IF NOT EXISTS artist_graph_cache (
    source_deezer_artist_id BIGINT NOT NULL,
    related_deezer_artist_id BIGINT NOT NULL,
    related_artist_name TEXT NOT NULL,
    related_artist_picture TEXT,
    related_nb_fan BIGINT,
    cached_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (source_deezer_artist_id, related_deezer_artist_id)
);

CREATE INDEX idx_graph_cache_source ON artist_graph_cache(source_deezer_artist_id);
CREATE INDEX idx_graph_cache_ttl ON artist_graph_cache(cached_at);


-- =============================================================================
-- artist_deezer_mapping: Cache of AURA artist slug → Deezer artist ID resolution.
-- =============================================================================
CREATE TABLE IF NOT EXISTS artist_deezer_mapping (
    aura_artist_id TEXT PRIMARY KEY,           -- AURA artist ID (artist:slug)
    deezer_artist_id BIGINT NOT NULL,
    artist_name TEXT NOT NULL,
    resolved_at TIMESTAMPTZ DEFAULT now(),
    confidence REAL DEFAULT 1.0
);


-- =============================================================================
-- ALTER download_jobs: Add is_discovery_preload flag.
-- Used to EXCLUDE discovery pre-downloads from the sync Room payload.
-- =============================================================================
ALTER TABLE download_jobs ADD COLUMN IF NOT EXISTS
    is_discovery_preload BOOLEAN NOT NULL DEFAULT FALSE;


-- =============================================================================
-- Row Level Security
-- =============================================================================
ALTER TABLE discovery_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_strategy_weights ENABLE ROW LEVEL SECURITY;
-- artist_graph_cache and artist_deezer_mapping are shared/system-level, no RLS needed.
